### PR TITLE
switch to peerDependencies

### PR DESCRIPTION
**Pull request by gavinr**
Inspired by https://github.com/jgravois/esri-leaflet-gp/pull/46#issuecomment-970504785, switched leaflet, esri-leaflet, and leaflet.markercluster to be peer dependencies

(more info in [previous discussion](https://github.com/Esri/esri-leaflet-cluster/pull/42#discussion_r751394977))

@jgravois if you have time could you please check this out - does it look correct?

### CODE REVIEW

**Review by jgravois — APPROVED** [review]
hey @gavinr 👋 

i definitely still think this is a viable way to eject and leave it up to consumers to pick whatever they want. if it helps, no one has complained since i made the same change in `esri-leaflet-gp`.

because of the new ambiguity, you _might_ consider adding a little more information to the CHANGELOG or creating a matrix in the README to explain what version ranges of this plugin correspond with what ranges of `esri-leaflet` and `leaflet`.

if i had it all to do over again i'd probably skip sharing rollup configs between esri-leaflet plugins, but such is life. 😄

ps. nothing wrong with checking in a v2 package-lock.json file, but if you're going to, you might want to run the travis tests on Node 16.x too.

**Review by jwasilgeo — APPROVED** [review]
Looks good to me, too, @gavinr. I also 2nd the pearls of wisdom @jgravois already dropped in this PR discussion.

**Comment by gavinr** [comment]
Thanks @jgravois! 

> might consider adding a little more information to the CHANGELOG 

So would this just be a note in the changelog like `This release of esri-leaflet-cluster was tested on leaflet@1.7.1 and esri-leaflet@3.0.5. Newer minor versions of those libraries will probably work, but be sure to test before upgrading.`?

> run the travis tests on Node 16.x too

Great point. Apparently the travis.org tests stopped working back in june 2021: https://travis-ci.org/github/Esri/esri-leaflet-cluster. I think we need to switch over to GitHub Actions or setup a connection to the new travis-ci.com for all esri-leaflet-* repos. I created an issue: https://github.com/Esri/esri-leaflet/issues/1318.

**Comment by jgravois** [comment]
> Newer minor versions of those libraries will probably work

I was thinking more about trying to tease out the _minimum_ version of Leaflet/Esri Leaflet for each major release here.

| esri-leaflet-cluster | esri-leaflet | leaflet |
| --- | --- | --- |
| v1.x.x | ? |  ? |
| v2.x.x | ? |  ? |

**Comment by gavinr** [comment]
This has been released in v3.0.0  https://github.com/Esri/esri-leaflet-cluster/releases/tag/v3.0.0

**Pull request merged**
